pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html styles.css app.js public/
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
